### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'MainThread'.

### ISSUE THREAD

**Issue by mcrrobinson** [aio-libs-abandoned/aioredis-py#1391]
### Describe the bug

Perhaps the same bug that happens in the syncronous version of the Redis client [here](https://github.com/redis/redis-py/issues/1339)
Happens when a SIGTERM is fired to the worker.

### To Reproduce

1. Create a uvicorn like server
2. Add aioredis on an endpoint
3. Call the endpoint
4. At some point CTRL+C to the server

### Expected behavior

```py
from aioredis import Redis
```

```py
redis = Redis(host='localhost', decode_responses=True)
redis_client = redis.client()
```
...
```py
@app.on_event("shutdown")
async def shutdown_event():
    await redis.connection_pool.disconnect()
    await redis.close()
```
Adding this didn't help as it did [here](https://github.com/redis/redis-py/issues/1339#issuecomment-629816688) 

Should close the server without erroring.

### Logs/tracebacks

```python-traceback
Exception ignored in: <function Redis.__del__ at 0x7fd693f889d0>
Traceback (most recent call last):
  File "/home/squash/miniconda3/lib/python3.9/site-packages/aioredis/client.py", line 1063, in __del__
  File "/home/squash/miniconda3/lib/python3.9/site-packages/aioredis/client.py", line 916, in __repr__
  File "/home/squash/miniconda3/lib/python3.9/site-packages/aioredis/connection.py", line 1337, in __repr__
  File "/home/squash/miniconda3/lib/python3.9/site-packages/aioredis/connection.py", line 653, in __init__
  File "/home/squash/miniconda3/envs/data_processing/lib/python3.9/asyncio/locks.py", line 81, in __init__
  File "/home/squash/miniconda3/envs/data_processing/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
RuntimeError: There is no current event loop in thread 'MainThread'.
```

### Python Version

```console
$ python --version
Python 3.9.7
```

### aioredis Version

```console
$ python -m pip show aioredis
Name: aioredis
Version: 2.0.1
Summary: asyncio (PEP 3156) Redis support
Home-page: https://github.com/aio-libs/aioredis-py
Author: 
Author-email: 
License: MIT
Location: /home/squash/miniconda3/lib/python3.9/site-packages
Requires: typing-extensions, async-timeout
Required-by:
```

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by iwpnd** [comment]
@UP2022742 this should be raised over at [redis-py](https://github.com/redis/redis-py) now as it is the new home of aioredis.

**Comment by iwpnd** [comment]
I think you have to either drop your `redis_client` and pass the `redis` only, or `redis_client.close()` in the shutdown. Otherwise the connection will not be cleaned up. @UP2022742
