### ISSUE TITLE
2.0.0a1: "AttributeError: 'RedisSSLContext' object has no attribute 'wrap_bio'"

### ISSUE THREAD

**Issue by egnor** [aio-libs-abandoned/aioredis-py#975]
Attempting to do a basic operation on a Heroku-hosted Redis instance over SSL, I got this error:

```
SSL handshake failed
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fdee58a14c0>
transport: <_SelectorSocketTransport fd=9 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 632, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 677, in _process_write_backlog
    ssldata = self._sslpipe.do_handshake(
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 117, in do_handshake
    self._sslobj = self._context.wrap_bio(
AttributeError: 'RedisSSLContext' object has no attribute 'wrap_bio'
```

(full trace at the bottom of the message). And indeed, RedisSSLContext does not have a wrap_bio method. Sadly I am not well versed in SSL internals so it's hard for me to chase further (though I can try). It's also possible this is secondary to some other SSL handshake issue? The stack traces confuse me a little bit.

```
8:48:31 PM web.1 |  ======== Running on http://0.0.0.0:5000 ========
8:48:31 PM web.1 |  (Press CTRL+C to quit)
8:48:47 PM web.1 |  SSL handshake failed
8:48:47 PM web.1 |  protocol: <asyncio.sslproto.SSLProtocol object at 0x7fdee58a14c0>
8:48:47 PM web.1 |  transport: <_SelectorSocketTransport fd=9 read=idle write=<idle, bufsize=0>>
8:48:47 PM web.1 |  Traceback (most recent call last):
8:48:47 PM web.1 |    File "/usr/lib/python3.8/asyncio/sslproto.py", line 632, in _on_handshake_complete
8:48:47 PM web.1 |      raise handshake_exc
8:48:47 PM web.1 |    File "/usr/lib/python3.8/asyncio/sslproto.py", line 677, in _process_write_backlog
8:48:47 PM web.1 |      ssldata = self._sslpipe.do_handshake(
8:48:47 PM web.1 |    File "/usr/lib/python3.8/asyncio/sslproto.py", line 117, in do_handshake
8:48:47 PM web.1 |      self._sslobj = self._context.wrap_bio(
8:48:47 PM web.1 |  AttributeError: 'RedisSSLContext' object has no attribute 'wrap_bio'
8:48:47 PM web.1 |  Error handling request
8:48:47 PM web.1 |  Traceback (most recent call last):
8:48:47 PM web.1 |    File "/home/egnor/.local/share/virtualenvs/puzzbot-dsJfNkNY/lib/python3.8/site-packages/aioredis/connection.py", line 654, in connect
8:48:47 PM web.1 |      await self._connect()
8:48:47 PM web.1 |    File "/home/egnor/.local/share/virtualenvs/puzzbot-dsJfNkNY/lib/python3.8/site-packages/aioredis/connection.py", line 681, in _connect
8:48:47 PM web.1 |      reader, writer = await asyncio.open_connection(
8:48:47 PM web.1 |    File "/usr/lib/python3.8/asyncio/streams.py", line 52, in open_connection
8:48:47 PM web.1 |      transport, _ = await loop.create_connection(
8:48:47 PM web.1 |    File "/usr/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
8:48:47 PM web.1 |      transport, protocol = await self._create_connection_transport(
8:48:47 PM web.1 |    File "/usr/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
8:48:47 PM web.1 |      await waiter
8:48:47 PM web.1 |    File "/usr/lib/python3.8/asyncio/sslproto.py", line 632, in _on_handshake_complete
8:48:47 PM web.1 |      raise handshake_exc
8:48:47 PM web.1 |    File "/usr/lib/python3.8/asyncio/sslproto.py", line 677, in _process_write_backlog
8:48:47 PM web.1 |      ssldata = self._sslpipe.do_handshake(
8:48:47 PM web.1 |    File "/usr/lib/python3.8/asyncio/sslproto.py", line 117, in do_handshake
8:48:47 PM web.1 |      self._sslobj = self._context.wrap_bio(
8:48:47 PM web.1 |  AttributeError: 'RedisSSLContext' object has no attribute 'wrap_bio'
8:48:47 PM web.1 |  The above exception was the direct cause of the following exception:
8:48:47 PM web.1 |  Traceback (most recent call last):
8:48:47 PM web.1 |    File "/home/egnor/.local/share/virtualenvs/puzzbot-dsJfNkNY/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
8:48:47 PM web.1 |      resp = await self._request_handler(request)
8:48:47 PM web.1 |    File "/home/egnor/.local/share/virtualenvs/puzzbot-dsJfNkNY/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
8:48:47 PM web.1 |      resp = await handler(request)
8:48:47 PM web.1 |    File "/home/egnor/source/puzzbot/puzzbot/app.py", line 66, in _handle_twilio_sms
8:48:47 PM web.1 |      twiml = await self._run_with_state(
8:48:47 PM web.1 |    File "/home/egnor/source/puzzbot/puzzbot/app.py", line 128, in _run_with_state
8:48:47 PM web.1 |      return await self.redis.transaction(
8:48:47 PM web.1 |    File "/home/egnor/.local/share/virtualenvs/puzzbot-dsJfNkNY/lib/python3.8/site-packages/aioredis/client.py", line 917, in transaction
8:48:47 PM web.1 |      await pipe.watch(*watches)
8:48:47 PM web.1 |    File "/home/egnor/.local/share/virtualenvs/puzzbot-dsJfNkNY/lib/python3.8/site-packages/aioredis/client.py", line 4554, in watch
8:48:47 PM web.1 |      return await self.execute_command("WATCH", *names)
8:48:47 PM web.1 |    File "/home/egnor/.local/share/virtualenvs/puzzbot-dsJfNkNY/lib/python3.8/site-packages/aioredis/client.py", line 4335, in immediate_execute_command
8:48:47 PM web.1 |      conn = await self.connection_pool.get_connection(
8:48:47 PM web.1 |    File "/home/egnor/.local/share/virtualenvs/puzzbot-dsJfNkNY/lib/python3.8/site-packages/aioredis/connection.py", line 1351, in get_connection
8:48:47 PM web.1 |      await connection.connect()
8:48:47 PM web.1 |    File "/home/egnor/.local/share/virtualenvs/puzzbot-dsJfNkNY/lib/python3.8/site-packages/aioredis/connection.py", line 662, in connect
8:48:47 PM web.1 |      raise ConnectionError(exc) from exc
8:48:47 PM web.1 |  aioredis.exceptions.ConnectionError: 'RedisSSLContext' object has no attribute 'wrap_bio'
```

**Comment by Andrew-Chen-Wang** [comment]
Is that 2.0.0a1 or latest on master?

**Comment by Andrew-Chen-Wang** [comment]
Not entirely sure what's going on either. Can you check if this is called:

https://github.com/aio-libs/aioredis-py/blob/965b4102ec7530179c92e0bc6e1462a78c55cf2f/aioredis/connection.py#L1027-L1037

**Comment by egnor** [comment]
It's 2.0.0a1 off pypi. I can try pulling latest from master if that would be interesting.

Best I can tell, that `get` method is in fact _not_ getting called before the `wrap_bio` call is attempted.

**Comment by egnor** [comment]
Ok at HEAD I get quite a bit further. Still having issues but I'll open a separate bug if I can't figure it out. Sorry for the false alarm / obsolete bug report!
